version: "3.0"


services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
    - .:/code
    command: nvidia-smi -l
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
